### ISSUE TITLE
Add support for Dependabot

### ISSUE THREAD

**Issue by brenno263** [sourceallies/interviews#11]
Some check repos use Dependabot to stay updated. We should look into integrating it into the monorepo.

It will be important to check some tests to make sure Dependabot doesn't create any regressions.

**Comment by tim-hornback-SAI** [comment]
It is now added in main, would not be surprised if we toss it.  I just set it to ignore patch versions.  I am not sure if setting it to ignore minor versions means it ignores minor _and_ patch versions.  I would expect it to, but the docs do not seem to explicitly say.
