### ISSUE TITLE
Java testing nice to haves

### ISSUE THREAD

**Issue by grey-lovelace** [sourceallies/interviews#12]
If you want to run java tests, you must do so from the command line.  You can also run them using the Java Debugger extension, but if you try, you must first switch it from lightweight mode to standard mode.  It would be nice to be able to do this by default, or at the very least add a note somewhere that lets people know how to start that process, as running tests from the command line is often uncomfortable for people.

**Comment by tim-hornback-SAI** [comment]
closed with #38
