### ISSUE TITLE
Cleaning up old repos

### ISSUE THREAD

**Issue by grey-lovelace** [sourceallies/interviews#7]

**Comment by tim-hornback-SAI** [comment]
Still needs archived:
- https://github.com/sourceallies/interview-javascript-template
- https://github.com/sourceallies/interview-python-template
- https://github.com/sourceallies/interview-go-check
- https://github.com/sourceallies/interview-typescript-check

**Comment by kylehoehns** [comment]
We're down to just the javascript and python template left - I've reached out to an owner to get those archived.

**Comment by kylehoehns** [comment]
These are all archived now
