### ISSUE TITLE
Incorporate "Problem" repositories into our solution

### ISSUE THREAD

**Issue by grey-lovelace** [sourceallies/interviews#9]
Jake Williamson is a good persona to talk to for this issue. Basically there are some specific repos we have made that have pre-built out code for refactoring for certain problem statements.  We want these to be able to leverage/benefit from our solution if possible.  We would NOT want these sample pieces of code to be public however.

**Comment by nbatterson** [comment]
I don't think we're going to pursue adding the problem code to this repo for a variety of issues, but if we want to discuss further feel free to reopen the issue.
